name = "create-desitnation-address"
main = "src/index.ts"
compatibility_date = "2023-11-21"


# APT_TOKEN and account_id is defined in cf dashboard

[[kv_namespaces]]
binding = "EMAIL_FIB"
id = "f285402c90e148f89e02fa5f443604cd"

